name: Dispatch Windows Images

on:
  workflow_call:
    inputs:
      push_image:
        type: boolean
        default: false
        description: Enable pushing images
      repo_version:
        type: string
        required: true
        description: Repository version

jobs:
  build-all-images:
    name: cuda${{ matrix.cuda_version}}-${{ matrix.edition }}
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2019, windows-2022]
        cuda_version: ["12.2", "11.1"]
        edition: [windows-2019, windows-2022]
        vs_version: ["2017", "2019", "2022"]
        exclude:
          # https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
          # Exclude Incompatible windows builds
          - runner: windows-2019
            edition: windows-2022
          - runner: windows-2022
            edition: windows-2019
          # Exclude MSVC 2022 and 11.1 as it is unsupported
          - vs_version: "2022"
            cuda_version: "11.1"
    uses: ./.github/workflows/build-and-push-windows-images.yml
    with:
      runner: ${{ matrix.runner }}
      win_edition: ${{ matrix.edition }}
      vs_version: ${{ matrix.vs_version }}
      cuda_version: ${{ matrix.cuda_version }}
      repo_version: ${{ inputs.repo_version }}
      push_image: ${{ inputs.push_image }}

  create-manifests:
    name: Create Windows image manifests
    needs: build-all-images
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        cuda_version: ["12.2", "11.1"]
        vs_version: ["2017", "2019", "2022"]
        exclude:
          # Exclude MSVC 2022 and 11.1 as it is unsupported
          - vs_version: "2022"
            cuda_version: "11.1"

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        if: ${{ inputs.push_image && vars.DOCKERHUB_REPOSITORY }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}

      - name: Create manifest
        if: ${{ inputs.push_image }}
        uses: ./.github/actions/create-and-push-manifest
        with:
          vs_version: ${{ matrix.vs_version }}
          cuda_version: ${{ matrix.cuda_version }}
          repo: ghcr.io/${{ github.repository }}
          repo_version: ${{ inputs.repo_version }}

      - name: Create manifest for dockerhub
        if: ${{ inputs.push_image && vars.DOCKERHUB_REPOSITORY }}
        uses: ./.github/actions/create-and-push-manifest
        with:
          vs_version: ${{ matrix.vs_version }}
          cuda_version: ${{ matrix.cuda_version }}
          repo: ${{ vars.DOCKERHUB_REPOSITORY }}
          repo_version: ${{ inputs.repo_version }}
